<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            ['product_offer' => 'Access Point', 'product_code' => 'O_ACC_POINT', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Account Inquiry', 'product_code' => 'O_ACCOUNT_INQUIRY', 'product_line' => 'Data Management & Analytics'],
            ['product_offer' => 'AI Contact Center', 'product_code' => 'O_AI_CONTACT_CENTER', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'AI Know', 'product_code' => 'O_AI_KNOW', 'product_line' => 'Digital Application'],
            ['product_offer' => 'AI-in-a-box', 'product_code' => 'O_AI_IN_A_BOX', 'product_line' => 'Digital Application'],
            ['product_offer' => 'Alibaba Cloud', 'product_code' => 'O_PC_ALIBABA', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Alibaba Cloud (INACTIVE)', 'product_code' => 'O_PUBLIC_CLOUD_ALIBABA', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Anti-DDoS - Arbor', 'product_code' => 'O_ANTIDDOS_ARBOR', 'product_line' => 'Security'],
            ['product_offer' => 'Anti-DDoS - Fortinet', 'product_code' => 'O_ANTIDDOS_FORTINET', 'product_line' => 'Security'],
            ['product_offer' => 'Anti-DDoS - NexusGuard', 'product_code' => 'O_ANTIDDOS_NEXUSGUARD', 'product_line' => 'Security'],
            ['product_offer' => 'Anti-DDoS (Inactive)', 'product_code' => 'O_ANTIDDOS_INACTIVE', 'product_line' => 'Security'],
            ['product_offer' => 'API-based Bulk Services', 'product_code' => 'O_API_BASED_BULK_SERVICES', 'product_line' => 'Mobility'],
            ['product_offer' => 'Automation Tools', 'product_code' => 'O_AUTOMATION_TOOLS', 'product_line' => 'Digital Application'],
            ['product_offer' => 'AWS Cloud', 'product_code' => 'O_PUBLIC_CLOUD_AWS', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Azure Cloud', 'product_code' => 'O_PC_AZURE', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Azure Cloud (INACTIVE)', 'product_code' => 'O_PUBLIC_CLOUD_AZURE', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'B2B Flex Mobile', 'product_code' => 'O_B2B_FLEX_MOBILE', 'product_line' => 'Mobility'],
            ['product_offer' => 'Bulk Service Community', 'product_code' => 'O_BULK_SERVICE_COMMUNITY', 'product_line' => 'Mobility'],
            ['product_offer' => 'Business Broadband', 'product_code' => 'O_BUSINESS_BROADBAND', 'product_line' => 'Connectivity'],
            ['product_offer' => 'Cache Peering', 'product_code' => 'O_CACHE_PEERING', 'product_line' => 'Connectivity'],
            ['product_offer' => 'Chrome', 'product_code' => 'O_CHROME', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Chrome Browser', 'product_code' => 'O_CHROME_BROWSER', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Cloud Access Security Broker (CASB) - Fortinet', 'product_code' => 'O_CLOUD_ACC_SEC_BROKER_FORTINET', 'product_line' => 'Security'],
            ['product_offer' => 'Cloud Access Security Broker (CASB) - Menlo Security', 'product_code' => 'O_CLOUD_ACC_SEC_BROKER_MENLO_SEC', 'product_line' => 'Security'],
            ['product_offer' => 'Cloud Contact Center', 'product_code' => 'O_CLOUD_CONTACT_CENTER', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Cloud Direct Connect', 'product_code' => 'O_CLOUD_DIRECT_CONNECT', 'product_line' => 'Connectivity'],
            ['product_offer' => 'Cloud PBX Offer', 'product_code' => 'O_CLOUD_PBX', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'CPaaS - RCS Business Messaging', 'product_code' => 'O_CPAAS_RBM', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'CPaaS - WhatsApp Business Platform', 'product_code' => 'O_CPAAS_WABA', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Custom AI Solutions', 'product_code' => 'O_CUSTOM_AI_SOLUTIONS', 'product_line' => 'Digital Application'],
            ['product_offer' => 'Custom Data Solutions', 'product_code' => 'O_CUSTOM_DATA_SOLUTIONS', 'product_line' => 'Data Management & Analytics'],
            ['product_offer' => 'Custom M2M Hardware', 'product_code' => 'O_CUSTOM_M2M_HDW', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Cyber Threat Intelligent Platform (CTIP) - Cisco', 'product_code' => 'O_CYBER_THREAT_INTELLIGENT_PLATFORM_CISCO', 'product_line' => 'Security'],
            ['product_offer' => 'Cyber Threat Intelligent Platform (CTIP) - CyberInt', 'product_code' => 'O_CYBER_THREAT_INTELLIGENT_PLATFORM_CYBERINT', 'product_line' => 'Security'],
            ['product_offer' => 'Cyber Threat Intelligent Platform (CTIP) - Cyfirma', 'product_code' => 'O_CYBER_THREAT_INTELLIGENT_PLATFORM_CYFIRMA', 'product_line' => 'Security'],
            ['product_offer' => 'Data Center Colocation [Other Partner]', 'product_code' => 'O_DATA_CENTER_COLOCATION_OTHER', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Data Center Colocation @ Jakarta City Center', 'product_code' => 'O_DATA_CENTER_COLOCATION_JKT', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Data Center Colocation @ Jatiluhur', 'product_code' => 'O_DATA_CENTER_COLOCATION_JATI', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Data Center Colocation @ TB Simatupang', 'product_code' => 'O_DATA_CENTER_COLOCATION_TBS', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Data Center Colocation @ Technopark BSD', 'product_code' => 'O_DATA_CENTER_COLOCATION_BSD', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Data Center Interconnect', 'product_code' => 'O_DATA_CENTER_INTERCONNECT', 'product_line' => 'Connectivity'],
            ['product_offer' => 'Data Lost Prevention (DLP) - DigitalGuardian', 'product_code' => 'O_DATA_LOST_PREVENTION_DIGITALGUARDIAN', 'product_line' => 'Security'],
            ['product_offer' => 'Data Lost Prevention (DLP) - Forcepoint', 'product_code' => 'O_DATA_LOST_PREVENTION_FORCEPOINT', 'product_line' => 'Security'],
            ['product_offer' => 'Data Visualization', 'product_code' => 'O_DATA_VISUALIZATION', 'product_line' => 'Data Management & Analytics'],
            ['product_offer' => 'Dedicated Internet', 'product_code' => 'O_DEDICATED_INTERNET', 'product_line' => 'Connectivity'],
            ['product_offer' => 'Deka Box (Object Storage)', 'product_code' => 'O_DEKA_BOX', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Deka DBaaS', 'product_code' => 'O_DEKA_DBAAS', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Deka DNS', 'product_code' => 'O_DEKA_DNS', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Deka Flexi (Hyperscaler Technology)', 'product_code' => 'O_DEKA_FLEXI', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Deka Harbor (Kubernetes Upstream)', 'product_code' => 'O_DEKA_HARBOR', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Deka License', 'product_code' => 'O_DEKA_LICENSE', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Deka Managed Service', 'product_code' => 'O_DEKA_MANAGED_SERVICE', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Deka Prime (VMWare Based)', 'product_code' => 'O_DEKA_PRIME', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Deka Rock (Kubernetes Red Hat Openshift)', 'product_code' => 'O_DEKA_ROCK', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Deka Vault - Backup', 'product_code' => 'O_DEKA_VAULT_BACKUP', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Deka Vault - VMWare Replication', 'product_code' => 'O_DEKA_VAULT_VMWARE_REPLICATION', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'DIOD', 'product_code' => 'O_DIOD', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Document Analyzer', 'product_code' => 'O_DOCUMENT_ANALYZER', 'product_line' => 'Digital Application'],
            ['product_offer' => 'EKYC', 'product_code' => 'O_EKYC', 'product_line' => 'Digital Application'],
            ['product_offer' => 'eKYC 2', 'product_code' => 'O_EKYC_2', 'product_line' => 'Digital Application'],
            ['product_offer' => 'Email Security - Barracuda', 'product_code' => 'O_EMAIL_SECURITY_BARRACUDA', 'product_line' => 'Security'],
            ['product_offer' => 'Email Security - Cisco', 'product_code' => 'O_EMAIL_SECURITY_CISCO', 'product_line' => 'Security'],
            ['product_offer' => 'Email Security - Forcepoint', 'product_code' => 'O_EMAIL_SECURITY_FORCEPOINT', 'product_line' => 'Security'],
            ['product_offer' => 'Email Security - Fortinet', 'product_code' => 'O_EMAIL_SECURITY_FORTINET', 'product_line' => 'Security'],
            ['product_offer' => 'Email Security - Perception Point', 'product_code' => 'O_EMAIL_SECURITY_PERCEPTION_POINT', 'product_line' => 'Security'],
            ['product_offer' => 'Email Security - Proofpoint', 'product_code' => 'O_EMAIL_SECURITY_PROOFPOINT', 'product_line' => 'Security'],
            ['product_offer' => 'Endpoint Detection and Response (EDR) - Cisco', 'product_code' => 'O_ENDPOINT_DETECTION_RESPONSE_CISCO', 'product_line' => 'Security'],
            ['product_offer' => 'Endpoint Detection and Response (EDR) - Crowdstrike', 'product_code' => 'O_ENDPOINT_DETECTION_RESPONSE_CROWDSTRIKE', 'product_line' => 'Security'],
            ['product_offer' => 'Endpoint Detection and Response (EDR) - Fortinet', 'product_code' => 'O_ENDPOINT_DETECTION_RESPONSE_FORTINET', 'product_line' => 'Security'],
            ['product_offer' => 'Endpoint Detection and Response (EDR) - Palo Alto', 'product_code' => 'O_ENDPOINT_DETECTION_RESPONSE_PALOALTO', 'product_line' => 'Security'],
            ['product_offer' => 'Endpoint Detection and Response (EDR) - SentinelOne', 'product_code' => 'O_ENDPOINT_DETECTION_RESPONSE_SENTINELONE', 'product_line' => 'Security'],
            ['product_offer' => 'Endpoint Detection and Response (EDR) - Tehtris', 'product_code' => 'O_ENDPOINT_DETECTION_RESPONSE_TEHTRIS', 'product_line' => 'Security'],
            ['product_offer' => 'Endpoint Detection and Response (EDR) - Trend Micro', 'product_code' => 'O_ENDPOINT_DETECTION_RESPONSE_TRENDMICRO', 'product_line' => 'Security'],
            ['product_offer' => 'Enterprise Broadband', 'product_code' => 'O_ENTERPRISE_BROADBAND', 'product_line' => 'Connectivity'],
            ['product_offer' => 'Enterprise Private Cells', 'product_code' => 'O_ENTERPRISE_PRIVATE_CELLS', 'product_line' => 'Connectivity'],
            ['product_offer' => 'EPN Private & Hybrid', 'product_code' => 'O_EPN_PRIVATE_HYBRID', 'product_line' => 'Connectivity'],
            ['product_offer' => 'EPN Public', 'product_code' => 'O_EPN_PUBLIC', 'product_line' => 'Connectivity'],
            ['product_offer' => 'Ethernet', 'product_code' => 'O_ETHERNET', 'product_line' => 'Connectivity'],
            ['product_offer' => 'Gift Telco', 'product_code' => 'O_GIFT_TELCO', 'product_line' => 'Mobility'],
            ['product_offer' => 'Google Cloud', 'product_code' => 'O_PUBLIC_CLOUD_GOOGLE', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Google Workspace Business and Enterprise', 'product_code' => 'O_GOOGLE_WORKSPACE_BUSINESS_ENT', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Google Workspace Education', 'product_code' => 'O_GOOGLE_WORKSPACE_EDUCATION', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Google Workspace Education', 'product_code' => 'O_GWS_EDUCATION', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Google Workspace Enterprise', 'product_code' => 'O_GOOGLE_WORKSPACE_ENT', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Google Workspace Frontline', 'product_code' => 'O_GOOGLE_WORKSPACE_FRONTLINE', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Huawei Cloud', 'product_code' => 'O_PUBLIC_CLOUD_HUAWEI', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Hytera Push-to-Talk Over Celular', 'product_code' => 'O_HYTERA_POC', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Identity & Privileged Access Management (IAM & PAM) - Airome', 'product_code' => 'O_IDENTITY_PRIVILEGED_ACCESS_MGMT_AIROME', 'product_line' => 'Security'],
            ['product_offer' => 'Identity & Privileged Access Management (IAM & PAM) - Cisco', 'product_code' => 'O_IDENTITY_PRIVILEGED_ACCESS_MGMT_CISCO', 'product_line' => 'Security'],
            ['product_offer' => 'Identity & Privileged Access Management (IAM & PAM) - CyberArk', 'product_code' => 'O_IDENTITY_PRIVILEGED_ACCESS_MGMT_CYBERARK', 'product_line' => 'Security'],
            ['product_offer' => 'Identity & Privileged Access Management (IAM & PAM) - Lookout', 'product_code' => 'O_IDENTITY_PRIVILEGED_ACCESS_MGMT_LOOKOUT', 'product_line' => 'Security'],
            ['product_offer' => 'Identity & Privileged Access Management (IAM & PAM) - Okta', 'product_code' => 'O_IDENTITY_PRIVILEGED_ACCESS_MGMT_OKTA', 'product_line' => 'Security'],
            ['product_offer' => 'Indosat CTI - RFI Addons', 'product_code' => 'O_INDOSAT_CTI_RFI_ADDONS', 'product_line' => 'Security'],
            ['product_offer' => 'Indosat CTI - Takedown Addons', 'product_code' => 'O_INDOSAT_CTI_TAKEDOWN_ADDONS', 'product_line' => 'Security'],
            ['product_offer' => 'IoT Bespoke', 'product_code' => 'O_IOT_BESPOKE', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'IoT Sensor', 'product_code' => 'O_IOT_SENSOR', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'IP PBX', 'product_code' => 'O_IP_PBX', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'IP Phone', 'product_code' => 'O_IP_PHONE', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'IP Transit', 'product_code' => 'O_IP_TRANSIT', 'product_line' => 'Connectivity'],
            ['product_offer' => 'IPhone Mobile Offer', 'product_code' => 'O_IPHONE_MOBILE_OFFER', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'IPVPN', 'product_code' => 'O_IPVPN', 'product_line' => 'Connectivity'],
            ['product_offer' => 'Lintasarta Cloudeka Deka LLM as a Service', 'product_code' => 'O_IOH_CLOUD_LLMAAS', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Lintasarta Cloudeka GPU as a Service (Baremetal as a Service)', 'product_code' => 'O_IOH_CLOUD_BMAAS', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Lintasarta Cloudeka GPU as a Service NVIDIA GPU (IaaS & PaaS)', 'product_code' => 'O_IOH_CLOUD_GPUAAS_GPU_IAAS_PAAS', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Lintasarta Cloudeka GPU as a Service NVIDIA H100 SXM (BMaaS)', 'product_code' => 'O_IOH_CLOUD_GPUAAS_BMAAS_H100', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Lintasarta Cloudeka GPUaaS NVIDIA vGPU (IaaS & PaaS)', 'product_code' => 'O_IOH_CLOUD_GPUAAS_VGPU_IAAS_PAAS', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'M2M Legacy Connectivity', 'product_code' => 'O_M2M_LEGACY_CONNECTIVITY', 'product_line' => 'Mobility'],
            ['product_offer' => 'M2M Managed Connectivity', 'product_code' => 'O_M2M_MANAGED_CONNECTIVITY', 'product_line' => 'Mobility'],
            ['product_offer' => 'M2M SIM Card', 'product_code' => 'O_M2M_SIM_CARD', 'product_line' => 'Mobility'],
            ['product_offer' => 'M2M Solution', 'product_code' => 'O_M2M_SOLUTION', 'product_line' => 'Mobility'],
            ['product_offer' => 'M2M Solution', 'product_code' => 'O_M2M_SOLUTION_2', 'product_line' => 'Mobility'],
            ['product_offer' => 'Managed Anti-DDoS - iCP Protection - NexusGuard', 'product_code' => 'O_ICP_PROTECTION_NEXUSGUARD', 'product_line' => 'Security'],
            ['product_offer' => 'Managed Anti-DDoS - iCP Protection (Inactive)', 'product_code' => 'O_ICP_PROTECTION_INACTIVE', 'product_line' => 'Security'],
            ['product_offer' => 'Managed Anti-DDoS - iDNS Protection - NexusGuard', 'product_code' => 'O_IDNS_PROTECTION_NEXUSGUARD', 'product_line' => 'Security'],
            ['product_offer' => 'Managed Anti-DDoS - iOrigin Protection - NexusGuard', 'product_code' => 'O_IORIGIN_PROTECTION_NEXUSGUARD', 'product_line' => 'Security'],
            ['product_offer' => 'Managed Anti-DDoS - iWeb App Protection - NexusGuard', 'product_code' => 'O_IWEB_APP_PROTECTION_NEXUSGUARD', 'product_line' => 'Security'],
            ['product_offer' => 'Managed Detection and Response (MDR) - SentinelOne', 'product_code' => 'O_MANAGED_DETECTION_RESPONSE_SENTINELONE', 'product_line' => 'Security'],
            ['product_offer' => 'Managed Detection and Response (MDR) (Inactive)', 'product_code' => 'O_MANAGED_DETECTION_RESPONSE_INACTIVE', 'product_line' => 'Security'],
            ['product_offer' => 'MBTS Solutions', 'product_code' => 'O_MTBS_SOL', 'product_line' => 'Connectivity'],
            ['product_offer' => 'Microsoft 365', 'product_code' => 'O_MS365', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Microsoft Teams', 'product_code' => 'O_MS_TEAMS', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Microsoft Teams Direct Routing', 'product_code' => 'O_MSTEAMS_DIRECT_ROUTING', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Mobile Application Protection - SecIron', 'product_code' => 'O_MOBILE_APPLICATION_PROTECTION_SECIRON', 'product_line' => 'Security'],
            ['product_offer' => 'Mobile Call Center', 'product_code' => 'O_MOBILE_CALL_CENTER', 'product_line' => 'Mobility'],
            ['product_offer' => 'Mobile Device Management (MDM) - Helios', 'product_code' => 'O_MOBILE_DEVICE_MANAGEMENT_HELIOS', 'product_line' => 'Security'],
            ['product_offer' => 'Mobile Device Management (MDM) - Kace', 'product_code' => 'O_MOBILE_DEVICE_MANAGEMENT_KACE', 'product_line' => 'Security'],
            ['product_offer' => 'Mobile Device Management (MDM) - Omnissa', 'product_code' => 'O_MOBILE_DEVICE_MANAGEMENT_OMNISSA', 'product_line' => 'Security'],
            ['product_offer' => 'Mobile Device Management (MDM) - Quest', 'product_code' => 'O_MOBILE_DEVICE_MANAGEMENT_QUEST', 'product_line' => 'Security'],
            ['product_offer' => 'Mobile Device Management (MDM) - Samsung', 'product_code' => 'O_MOBILE_DEVICE_MANAGEMENT_SAMSUNG', 'product_line' => 'Security'],
            ['product_offer' => 'Mobile Threat Defence (MTD) - Checkpoint', 'product_code' => 'O_MOBILE_THREAT_DEFENCE_CHECKPOINT', 'product_line' => 'Security'],
            ['product_offer' => 'Mobile Threat Defence (MTD) - SentinelOne', 'product_code' => 'O_MOBILE_THREAT_DEFENCE_SENTINELONE', 'product_line' => 'Security'],
            ['product_offer' => 'Modem', 'product_code' => 'O_MODEM', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'MP Product Sample Prototype Offer', 'product_code' => 'O_MP_PRD_SAMPLE', 'product_line' => 'Mobility'],
            ['product_offer' => 'Network Detection and Response (NDR) - DarkTrace', 'product_code' => 'O_NETWORK_DETECTION_RESPONSE_DARKTRACE', 'product_line' => 'Security'],
            ['product_offer' => 'Network Detection and Response (NDR) - Extrahop', 'product_code' => 'O_NETWORK_DETECTION_RESPONSE_EXTRAHOP', 'product_line' => 'Security'],
            ['product_offer' => 'Network Detection and Response (NDR) - Trellix (McAfee & Fireeye)', 'product_code' => 'O_NETWORK_DETECTION_RESPONSE_TRELLIX', 'product_line' => 'Security'],
            ['product_offer' => 'Network Detection and Response (NDR) - Vectra', 'product_code' => 'O_NETWORK_DETECTION_RESPONSE_VECTRA', 'product_line' => 'Security'],
            ['product_offer' => 'Network Infra Services', 'product_code' => 'O_NETWORK_INFRA_SERV', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Network Infra Solution', 'product_code' => 'O_NETWORK_INFRA_SOLUTION', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Network Packet Broker (NPB) - Extrahop', 'product_code' => 'O_NET_PACKET_BROKER_EXTRAHOP', 'product_line' => 'Security'],
            ['product_offer' => 'Network Packet Broker (NPB) - Keysight', 'product_code' => 'O_NET_PACKET_BROKER_KEYSIGHT', 'product_line' => 'Security'],
            ['product_offer' => 'Next-Gen Firewall', 'product_code' => 'O_NEXTGEN_FIREWALL', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Next-Gen Firewall - Checkpoint', 'product_code' => 'O_NEXTGEN_FIREWALL_CHECKPOINT', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Next-Gen Firewall - Cisco', 'product_code' => 'O_NEXTGEN_FIREWALL_CISCO', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Next-Gen Firewall - Forcepoint', 'product_code' => 'O_NEXTGEN_FIREWALL_FORCEPOINT', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Next-Gen Firewall - Fortinet', 'product_code' => 'O_NEXTGEN_FIREWALL_FORTINET', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Next-Gen Firewall - Palo Alto', 'product_code' => 'O_NEXTGEN_FIREWALL_PALO_ALTO', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Next-Gen Firewall - Sophos', 'product_code' => 'O_NEXTGEN_FIREWALL_SOPHOS', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Number Masking', 'product_code' => 'O_NUMBER_MASKING', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Office 365', 'product_code' => 'O_OFFICE365', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Omni Digital Advertisement', 'product_code' => 'O_ODA', 'product_line' => 'Data Management & Analytics'],
            ['product_offer' => 'Optical', 'product_code' => 'O_OPTICAL', 'product_line' => 'Connectivity'],
            ['product_offer' => 'Other M2M Hardware', 'product_code' => 'O_OTHER_M2M_HDW', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Payment Device', 'product_code' => 'O_PAYMENT_DEVICE', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'PC / Notebook', 'product_code' => 'O_PC_NOTEBOOK', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Platinum Business', 'product_code' => 'O_PLATINUM_BUSINESS', 'product_line' => 'Mobility'],
            ['product_offer' => 'Platinum Business Device', 'product_code' => 'O_PLATINUM_BUSINESS_DEVICE', 'product_line' => 'Mobility'],
            ['product_offer' => 'Portal-based Bulk Services', 'product_code' => 'O_PORTAL_BASED_BULK_SERVICES', 'product_line' => 'Mobility'],
            ['product_offer' => 'Prime Biz', 'product_code' => 'O_PRIME_BIZ', 'product_line' => 'Mobility'],
            ['product_offer' => 'Private Network Interconnect (PNI)', 'product_code' => 'O_PNI', 'product_line' => 'Connectivity'],
            ['product_offer' => 'Pro Best', 'product_code' => 'O_PRO_BEST', 'product_line' => 'Mobility'],
            ['product_offer' => 'Pro Biz', 'product_code' => 'O_PRO_BIZ', 'product_line' => 'Mobility'],
            ['product_offer' => 'Pro Freedom Apps', 'product_code' => 'O_PRO_FREEDOM_APPS', 'product_line' => 'Mobility'],
            ['product_offer' => 'Pro Freedom Biz', 'product_code' => 'O_PRO_FREEDOM_BIZ', 'product_line' => 'Mobility'],
            ['product_offer' => 'Robot', 'product_code' => 'O_ROBOT', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Router', 'product_code' => 'O_ROUTER', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'SD-WAN Security', 'product_code' => 'O_SDWAN_SECURITY', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'SDA - WhatsApp Business Account', 'product_code' => 'O_SDA_WABA', 'product_line' => 'Data Management & Analytics'],
            ['product_offer' => 'Security Information and Event Management (SIEM) - Cisco', 'product_code' => 'O_SEC_INFO_AND_EVENT_MGMT_CISCO', 'product_line' => 'Security'],
            ['product_offer' => 'Security Information and Event Management (SIEM) - Fortinet', 'product_code' => 'O_SEC_INFO_AND_EVENT_MGMT_FORTINET', 'product_line' => 'Security'],
            ['product_offer' => 'Security Information and Event Management (SIEM) - Splunk', 'product_code' => 'O_SEC_INFO_AND_EVENT_MGMT_SPLUNK', 'product_line' => 'Security'],
            ['product_offer' => 'Security Operational Center (SOC) - Lintasarta', 'product_code' => 'O_SECURITY_OPERATIONAL_CENTER_LINTASARTA', 'product_line' => 'Security'],
            ['product_offer' => 'Server', 'product_code' => 'O_SERVER', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Services', 'product_code' => 'O_SERV', 'product_line' => 'Services'],
            ['product_offer' => 'Silent Authentication', 'product_code' => 'O_SILENT_AUTHENTICATION', 'product_line' => 'Data Management & Analytics'],
            ['product_offer' => 'SIP Trunk Plus Fixed Number', 'product_code' => 'O_SIP_TRUNK_PLUS_FIXED', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'SIP Trunk Plus Fixed Number', 'product_code' => 'O_SIP_TRUNK_PLUS_FIXED_TEST', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'SIP Trunk Plus Mobile Number', 'product_code' => 'O_SIP_TRUNK_PLUS_MOBILE', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'SIP Trunking', 'product_code' => 'O_SIP_TRUNKING', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'SIP Trunking Number', 'product_code' => 'O_SIP_TRUNKING_NUMBER', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Smart Building Application', 'product_code' => 'O_SMART_BUILDING_APPS', 'product_line' => 'Digital Application'],
            ['product_offer' => 'Smart Building Device', 'product_code' => 'O_SMART_BUILDING_DEVICE', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Smart Collaboration', 'product_code' => 'O_SMART_COLLABORATION', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Smart Device', 'product_code' => 'O_SMART_DEVICE', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Smart Digital Advertisement', 'product_code' => 'O_SDA', 'product_line' => 'Data Management & Analytics'],
            ['product_offer' => 'Smart Industry Application', 'product_code' => 'O_SMART_INDUSTRY_APPS', 'product_line' => 'Digital Application'],
            ['product_offer' => 'Smart Industry Device', 'product_code' => 'O_SMART_INDUSTRY_DEVICE', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Smart Mobility Application', 'product_code' => 'O_SMART_MOBILITY_APPS', 'product_line' => 'Digital Application'],
            ['product_offer' => 'Smart Mobility Application (UNUSED)', 'product_code' => 'O_SMART_MOBILITY_APPS_UNUSED', 'product_line' => 'Digital Application'],
            ['product_offer' => 'Smart Mobility Device', 'product_code' => 'O_SMART_MOBILITY_DEVICE', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'SMS A2P', 'product_code' => 'O_SMS_A2P', 'product_line' => 'Mobility'],
            ['product_offer' => 'SMS Business', 'product_code' => 'O_SMS_BUSINESS', 'product_line' => 'Mobility'],
            ['product_offer' => 'Solution Offer', 'product_code' => 'O_SOL_OFFER', 'product_line' => 'None'],
            ['product_offer' => 'Static/Dynamic Application Security Testing (AST) - CheckMarx', 'product_code' => 'O_STATIC_DYNAMIC_APPLICATION_SECURITY_TESTING_CHECKMARX', 'product_line' => 'Security'],
            ['product_offer' => 'Static/Dynamic Application Security Testing (AST) - Synopsys', 'product_code' => 'O_STATIC_DYNAMIC_APPLICATION_SECURITY_TESTING_SYNOPSYS', 'product_line' => 'Security'],
            ['product_offer' => 'Storage', 'product_code' => 'O_STORAGE', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Storage Network', 'product_code' => 'O_STORAGE_NETWORK', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Supported Peripheral', 'product_code' => 'O_SUPPORTED_PERIPHERAL', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Switch', 'product_code' => 'O_SWITCH', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Telco Scoring - Co-Modeling', 'product_code' => 'O_TELCO_SCORING_CO_MODELING', 'product_line' => 'Data Management & Analytics'],
            ['product_offer' => 'Telco Scoring - Ready to Use', 'product_code' => 'O_TELCO_SCORING_READY_TO_USE', 'product_line' => 'Data Management & Analytics'],
            ['product_offer' => 'Tencent Cloud', 'product_code' => 'O_PUBLIC_CLOUD_TENCENT', 'product_line' => 'DC & Cloud'],
            ['product_offer' => 'Voice Authentication', 'product_code' => 'O_VOICE_AUTHENTICATION', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Voice Broadcast', 'product_code' => 'O_VOICE_BROADCAST', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'VoIP Gateway', 'product_code' => 'O_VOIP_GATEWAY', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Vulnerability Management & Penetration Testing (VAPT) - Pentera', 'product_code' => 'O_VULNERABILITY_MGMT_PENTEST_PENTERA', 'product_line' => 'Security'],
            ['product_offer' => 'Vulnerability Management & Penetration Testing (VAPT) - Rapid7', 'product_code' => 'O_VULNERABILITY_MGMT_PENTEST_RAPID7', 'product_line' => 'Security'],
            ['product_offer' => 'Vulnerability Management & Penetration Testing (VAPT) - RidgeBot', 'product_code' => 'O_VULNERABILITY_MGMT_PENTEST_RIDGEBOT', 'product_line' => 'Security'],
            ['product_offer' => 'Vulnerability Management & Penetration Testing (VAPT) - Tenable', 'product_code' => 'O_VULNERABILITY_MGMT_PENTEST_TENABLE', 'product_line' => 'Security'],
            ['product_offer' => 'Web Application Firewall (WAF)', 'product_code' => 'O_WEB_APPLICATION_FIREWALL', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Web Application Firewall (WAF) - Checkpoint', 'product_code' => 'O_WEB_APPLICATION_FIREWALL_CHECKPOINT', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Web Application Firewall (WAF) - F5', 'product_code' => 'O_WEB_APPLICATION_FIREWALL_F5', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Web Application Firewall (WAF) - Fortinet', 'product_code' => 'O_WEB_APPLICATION_FIREWALL_FORTINET', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Web Application Firewall (WAF) - Imperva', 'product_code' => 'O_WEB_APPLICATION_FIREWALL_IMPERVA', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Web Application Firewall (WAF) - NexusGuard', 'product_code' => 'O_WEB_APPLICATION_FIREWALL_NEXUXGUARD', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Yeastar IP PBX', 'product_code' => 'O_YEASTAR_IP_PBX', 'product_line' => 'Devices & Hardware'],
            ['product_offer' => 'Zero Trust Network Access (ZTNA) - Cisco', 'product_code' => 'O_ZERO_TRUST_NET_ACC_CISCO', 'product_line' => 'Security'],
            ['product_offer' => 'Zero Trust Network Access (ZTNA) - Fortinet', 'product_code' => 'O_ZERO_TRUST_NET_ACC_FORTINET', 'product_line' => 'Security'],
            ['product_offer' => 'Zero Trust Network Access (ZTNA) - Menlo Security', 'product_code' => 'O_ZERO_TRUST_NET_ACC_MENLO_SEC', 'product_line' => 'Security'],
            ['product_offer' => 'Zero Trust Network Access (ZTNA) - Palo Alto', 'product_code' => 'O_ZERO_TRUST_NET_ACC_PALOALTO', 'product_line' => 'Security'],
            ['product_offer' => 'Zoom Contact Center', 'product_code' => 'O_ZOOM_CONTACT_CENTER', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Zoom Phone', 'product_code' => 'O_ZOOM_PHONE', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Zoom Rooms', 'product_code' => 'O_ZOOM_ROOMS', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Zoom Workplace', 'product_code' => 'O_ZOOM_WORKPLACE', 'product_line' => 'Communication & Collaboration'],
            ['product_offer' => 'Zoom Workvivo', 'product_code' => 'O_ZOOM_WORKVIVO', 'product_line' => 'Communication & Collaboration'],
        ];

        Product::upsert($products, ['product_code'], ['product_offer', 'product_line']);
    }
}
